# Generated by Django 5.2.17 on 2026-09-30 18:38

import django.core.validators
import django.db.models.deletion
import valour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('notes', models.TextField(blank=True, help_text='Written lesson notes. HTML is escaped on the React site.')),
                ('estimated_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_notice', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('ordering', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(default='ValourTech Sectors', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('whatsapp_url', models.URLField(blank=True, max_length=500)),
                ('contact_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site and contact details',
                'verbose_name_plural': 'site and contact details',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(blank=True, help_text='Optional account name shown on the site.', max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('ordering', 'platform', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('description', models.TextField(blank=True, help_text='Plain text; formatting is handled by the site.')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_notice', models.CharField(blank=True, default='This course is currently locked.', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('ordering', 'title'),
                'indexes': [models.Index(fields=['is_published', 'ordering'], name='valour_cour_is_publ_3b93bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word document')], max_length=12)),
                ('file', models.FileField(upload_to=valour.models.material_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx')), valour.models.validate_material_size])),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_notice', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='valour.lesson')),
            ],
            options={
                'ordering': ('ordering', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_notice', models.CharField(blank=True, max_length=240)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='valour.course')),
            ],
            options={
                'ordering': ('ordering', 'id'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='valour.section'),
        ),
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='For example: Resistor colour code walkthrough', max_length=160)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('url', models.URLField(help_text='Paste the original public post/video URL.', max_length=500)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='valour.lesson')),
            ],
            options={
                'ordering': ('ordering', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['course', 'is_published', 'ordering'], name='valour_sect_course__02508a_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['section', 'is_published', 'ordering'], name='valour_less_section_532d3b_idx'),
        ),
    ]
