# Generated by Django 5.2.17 on 2026-09-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='safety_notice',
            field=models.CharField(blank=True, help_text='Optional safety guidance shown before the lesson content.', max_length=500),
        ),
    ]
