# Generated by Django 5.2.17 on 2026-10-01 14:37

import django.core.validators
import valour.models
import valour.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valour', '0002_lesson_safety_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to=valour.models.material_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx')), valour.models.validate_material_size, valour.validators.validate_material_content]),
        ),
    ]
