# Generated by Django 5.2.17 on 2026-10-01 18:42

import valour.models
import valour.validators
from django.db import migrations, models


def _row_level_security(apps, schema_editor, *, statement):
    """Apply 0004's Supabase protection to the table this migration creates.

    Migrations stay self-contained, so the helper is repeated here rather than
    imported from a module whose name starts with a digit.
    """
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return
    table = apps.get_model("valour", "Learner")._meta.db_table
    with connection.cursor() as cursor:
        if table in set(connection.introspection.table_names(cursor)):
            cursor.execute(f"ALTER TABLE {connection.ops.quote_name(table)} {statement} ROW LEVEL SECURITY")


def enable_row_level_security(apps, schema_editor):
    _row_level_security(apps, schema_editor, statement="ENABLE")


def disable_row_level_security(apps, schema_editor):
    _row_level_security(apps, schema_editor, statement="DISABLE")


class Migration(migrations.Migration):

    dependencies = [
        ('valour', '0004_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='Stored lowercased; this is what the learner signs in with.', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Contact number captured at sign-up, for example +234 803 123 4567.', max_length=32, validators=[valour.validators.validate_learner_phone])),
                ('is_active', models.BooleanField(default=True, help_text='Deactivated learners cannot sign in. The record is kept.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('locked_until', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'learner',
                'verbose_name_plural': 'learners',
                'ordering': ('-created_at', 'email'),
            },
            managers=[
                ('objects', valour.models.LearnerManager()),
            ],
        ),
        migrations.RunPython(enable_row_level_security, reverse_code=disable_row_level_security),
    ]
