# Generated by Django 5.2.17 on 2026-10-01 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _row_level_security(apps, schema_editor, *, statement):
    """Apply 0004's Supabase protection to the table this migration creates.

    Migrations stay self-contained, so the helper is repeated here rather than
    imported from a module whose name starts with a digit.
    """
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return
    table = apps.get_model("valour", "RegistrationInvite")._meta.db_table
    with connection.cursor() as cursor:
        if table in set(connection.introspection.table_names(cursor)):
            cursor.execute(f"ALTER TABLE {connection.ops.quote_name(table)} {statement} ROW LEVEL SECURITY")


def enable_row_level_security(apps, schema_editor):
    _row_level_security(apps, schema_editor, statement="ENABLE")


def disable_row_level_security(apps, schema_editor):
    _row_level_security(apps, schema_editor, statement="DISABLE")


class Migration(migrations.Migration):

    dependencies = [
        ('valour', '0005_learner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('note', models.CharField(blank=True, help_text='A private reminder for staff, for example who this link was sent to. Never shown on the site.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave empty for a link that stays usable until it is spent or revoked.', null=True)),
                ('is_revoked', models.BooleanField(default=False, help_text='A revoked link stops working at once.')),
                ('used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The staff account that generated this link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_invites', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.OneToOneField(blank=True, editable=False, help_text='The account this link created. A spent link cannot be used again.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_invite', to='valour.learner')),
            ],
            options={
                'verbose_name': 'registration invite',
                'verbose_name_plural': 'registration invites',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RunPython(enable_row_level_security, reverse_code=disable_row_level_security),
    ]
